server:
  port: 3344
spring:
  application:
    name: microservicecloud-config   #对方暴露的服务名称
  cloud:
    config:
      server:
        git:  #github上的git仓库名字
          uri: https://github.com/fm00110/microservicecloud-config.git

          
          